### ISSUE TITLE
FRIDA - can we add?

### ISSUE THREAD

**Issue by PDX4N6** [REMnux/salt-states#109]
https://frida.re/docs/home/

**Comment by lennyzeltser** [comment]
I'm familiar with running Frida on Windows, but I'm uncertain how it would be used on Linux. The [Frida documentation page for Linux](https://frida.re/docs/examples/linux/) wasn't particularly forthcoming. Could you clarify what use-cases you had in mind?

**Comment by PDX4N6** [comment]
For starters thank you for making such a great VM, it is incredibly generous of you and your team to give such a great resource to the community.  I was thinking it would be great for conducting analysis of processes as well as mobile applications.  Radare has r2frida framework that works with FRIDA.  I have only installed it with pip on my MAC so I have never installed it on a linux system before.

Thank you again fro all the fast responses.

cheers

Aaron

**Comment by PDX4N6** [comment]
Here is a great video of r2frida

https://www.youtube.com/watch?v=URyd4bcV-Ik <https://www.youtube.com/watch?v=URyd4bcV-Ik>

cheers

Aaron

**Comment by PDX4N6** [comment]
Oh and a side note I c there is a FOR710 domain, looking forward to the class when it drops. 😄

**Comment by lennyzeltser** [comment]
Thank you for the Frida suggestion. It's now in the distro, thanks to @digitalsleuth.

**Comment by PDX4N6** [comment]
Awesome thank u
