### ISSUE TITLE
MobSF- can we add?

### ISSUE THREAD

**Issue by PDX4N6** [REMnux/salt-states#110]
https://github.com/MobSF/Mobile-Security-Framework-MobSF

**Comment by lennyzeltser** [comment]
This browser app seems too heavy for REMnux. I think people will be better off running it as a Docker image, which I see is available as `opensecurity/mobile-security-framework-mobsf`.

**Comment by PDX4N6** [comment]
Probably very true, that you for taking a look at it.

cheers

Aaron
