### ISSUE TITLE
RETDEC - can we add?

### ISSUE THREAD

**Issue by PDX4N6** [REMnux/salt-states#112]
https://github.com/avast/retdec

**Comment by lennyzeltser** [comment]
What a useful tool, thanks for the recommendation! It's too heavy to install directly as part of the distro, but maybe we'll make it available as a Docker image.

**Comment by PDX4N6** [comment]
Awesome. Thank u.

**Comment by lennyzeltser** [comment]
@digitalsleuth built the Dockerfile, and the [remnux/retdec Docker image is now on Docker Hub](https://hub.docker.com/repository/docker/remnux/retdec).

**Comment by PDX4N6** [comment]
Awesome

Thank you so much for doing all the work this 

Cheers

Aaron
