### ISSUE TITLE
Gnome Terminal 3.28.2 (Remnux 7) - Resolution Issue at Max Size

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#113]
Sample:

![image](https://user-images.githubusercontent.com/17726673/87369485-9c61d680-c54e-11ea-8c81-6259fc84bca1.png)

This is a placeholder and not urgent. "Unmaximize" makes the issue go away.

**Comment by lennyzeltser** [comment]
This is good to capture as a known issue in the archive, but I'm going to close this one, because I don't think I'll work on fixing this given the easy workaround.
