### ISSUE TITLE
stringsifter - any chance we can add?

### ISSUE THREAD

**Issue by PDX4N6** [REMnux/salt-states#117]
really like this tool a lot
https://github.com/fireeye/stringsifter

**Comment by lennyzeltser** [comment]
I like stringsifter as an idea, but I haven't found it especially useful in my own experience. When I look at strings, I find it relatively easy to identify "interesting" strings on my own. And the tool's use of ML to highlight strings of interest hasn't shown me anything I didn't spot myself. But I haven't tested the tool extensively, so it's very possible I'm under-appreciating it.

Have you found it particularly useful?

**Comment by PDX4N6** [comment]
I think it is more useful to newer analyst as it pulls all the more likely relevant strings to the top and I have actually found strings that way that I had skipped over previously.  If it isn’t to heavy for the distro I know I would use it a lot.

**Comment by lennyzeltser** [comment]
OK, good points. I added the tool to the distro. Thanks for the idea.

**Comment by PDX4N6** [comment]
Absolutely and thank you.

Something I think that would be very cool and I would be willing to assist with it if it were to become a thing, would to make a video series of all the tools on the VM and some basic use case scenarios, just put balling a n idea is all

Again thank you for all the work on this and c u at the summit tomorrow, I am actually presenting first thing in the morning hahahaha

cheers

Aaron

**Comment by lennyzeltser** [comment]
Sweet, that's one of the presentations I'm hoping to attend!

And yes, a series that showcases the various tools would be amazing! There is a placeholder for linking to content like this here: https://docs.remnux.org/tips/remnux-tool-tips

**Comment by PDX4N6** [comment]
Awesome,

Thank you for taking the time

cheers

Aaron
