### ISSUE TITLE
HawkEye : one more to look at 

### ISSUE THREAD

**Issue by PDX4N6** [REMnux/salt-states#122]
if its not too late what do think of this https://github.com/N1ght-W0lf/HawkEye/blob/master/README.md

**Comment by digitalsleuth** [comment]
Looking at this now, but unable to get any samples to work successfully with this. Any chance you have one or two which you know work, when running this tool in a Linux environment?

**Comment by PDX4N6** [comment]
You know it probably won’t run-on linux I was thinking maybe with wine but it looks like it would need to run in a windows VM

Ill play with. It some too and see.

Thanks again

Aaron

**Comment by digitalsleuth** [comment]
Well, it 'technically' runs on Linux, but not with the analysis feature it's intended to use. It does look like it needs to be on Windows, so this might not be a good fit for REMnux.
________________________________

**Comment by PDX4N6** [comment]
Sounds good thank you again for looking into it, might be worth adding to my windows RE VM
Enjoy your evening

cheers

Aaron
