### ISSUE TITLE
Oletools not installing correctly causing errors in installation

### ISSUE THREAD

**Issue by jknyght9** [REMnux/salt-states#137]
In the process of installing REMnux on a fresh ubuntu 18.04 VM, I would get an installation error. Upon reviewing the `saltstack.log` I discovered a number of the oletools with "path not found." The installer was looking for the tool in `/usr/local/bin` however the tools were installed in `/usr/bin`.

As a work around, I just copied the oletool binaries to the folder the installer was looking at.

```
# sudo cp /usr/bin/ole* /usr/local/bin/
```

Please look into this issue.

**Comment by digitalsleuth** [comment]
Hi @jknyght9 , could you attach your saltstack.log so we can review the issue further?

Thanks!

**Comment by jknyght9** [comment]
Unfortunately the log was overwritten when I successfully installed the software.

**Comment by lennyzeltser** [comment]
Thanks for letting us know, @jknyght9! I tried to replicate the problem in several ways, but have been unable to do so--oletools kept getting installed under `/usr/local`, as expected.

We'll keep this issue open for a bit in case someone else comes across it, too, and we can start piecing together a pattern.

**Comment by digitalsleuth** [comment]
I just finished trying the same thing and ended up with the same result as @lennyzeltser. I know you said that you used a fresh 18.04 VM, but do you think there was anything unique about your Ubuntu installation? If you could provide more information about the VM you used, that may also help.
Otherwise, like @lennyzeltser mentioned, we may just have to wait until it happens again.

Thanks for reaching out!

**Comment by digitalsleuth** [comment]
Just managed to reproduce the error. @jknyght9 is correct, oletools is now installing into /usr/bin by default, this causing the file.replace commands to fail.

```
# [INFO    ] Executing state file.replace for [/usr/local/bin/olevba]
# [ERROR   ] /usr/local/bin/olevba: file not found
```
Working on the fix now.
Thanks again for bringing this up @jknyght9

**Comment by lennyzeltser** [comment]
Thanks for resolving this issue, @digitalsleuth! Thanks for reporting it, @jknyght9!

**Comment by jknyght9** [comment]
confirmed fixed
