### ISSUE TITLE
Viper tools failing install

### ISSUE THREAD

**Issue by jknyght9** [REMnux/salt-states#139]
Sorry guys,

Environment:
- fresh install of Ubuntu 18.04.5 Desktop
- minimal install (only desktop and SSH)
- completed OS updates
- virtual machine in VMware Fusion

Pulled remnux-cli, verified, completed your documentation steps, and installed using the `sudo remnux install` command. Install failed and upon reviewing the saltstack log, I got a "one or more requisite failed: remnux.python-packages.viper-framework..."

Attaching the log file.
[saltstack.log](https://github.com/REMnux/salt-states/files/5169594/saltstack.log)

**Comment by digitalsleuth** [comment]
Can you check the permissions on your /home/jake/.viper directory and let us know what it shows?

**Comment by digitalsleuth** [comment]
Also looks like a recent change (last two weeks) to the requirements file has caused a conflict. It has both bitstring==3.1.6 and 3.1.7 in it. Will look into addressing this.

**Comment by lennyzeltser** [comment]
Addressed in https://github.com/REMnux/salt-states/pull/140. Thanks for the workaround, @digitalsleuth, and for reporting the issue, @jknyght9!

**Comment by jknyght9** [comment]
Was there a recent push? I am still receiving errors from viper tools.

**Comment by lennyzeltser** [comment]
Another issue popped up with Viper. We are looking into it.

**Comment by jknyght9** [comment]
Thank you guys for all your work.

**Comment by lennyzeltser** [comment]
Should be fixed now, thanks to @digitalsleuth. Please give it a try, @jknyght9
