### ISSUE TITLE
upgrade always fails without clear reason (to me) + performance question

### ISSUE THREAD

**Issue by kryponix** [REMnux/salt-states#141]
[saltstack.log](https://github.com/REMnux/salt-states/files/5209754/saltstack.log)
After following the simple steps to get vbox virtual appliance running, I try remnux upgrade and get:
...
>> Running: ssh <--------(always fails here)
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:551:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

when I go to saltstack.log in the directory that matches the REMnux version I'm upgrading to, after grep searching for [ERROR   ] lines (apart from those 'cannot parse lines..') I only find:
[ERROR   ] Command '['/opt/viper/bin/pip3', 'install', '--requirement', '/home/remnux/.viper/modules/requirements.txt', '--disable-pip-version-check', '--upgrade']' failed with return code: 1
 [ERROR   ] stdout: Requirement already up-to-date: androguard==3.3.5 in /opt/viper/lib/python3.6/site-packages (from -r /home/remnux/.viper/modules/requirements.txt (line 4)) (3.3.5)
...
 [ERROR   ] stderr: WARNING: The directory '/home/remnux/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Package 'scrapysplashwrapper' requires a different Python: 3.6.9 not in '>=3.7,<4.0'
 [ERROR   ] retcode: 1
 [ERROR   ] Unable to process requirements file "/home/remnux/.viper/modules/requirements.txt". Error: Requirement already up-to-date: androguard==3.3.5 in /opt/viper/lib/python3.6/site-packages (from -r /home/remnux/.viper/modules/requirements.txt (line 4)) (3.3.5)

But the installation continues...

I tried also installing the new Guest tools, since vm seems pretty slow (even though it's running into a decent host) with default conf. Definitely much slower than v6. Of course tried also cleaning apt caches etc. as indicated before trying each time.
Always fails at the same step (which might rule out network load or connectivity problems)

Might be sth I'm doing incorrectly but it's difficult since upgrading is literally the first action I try on the provided vm.
Attached the log file for reference.
Help apreciated.

**Comment by lennyzeltser** [comment]
The installation error looks like there's an issue with a recently-updated Viper Framework. We're looking into it.

Regarding performance: Version 7 of REMnux definitely requires more resources than version 6, because REMnux now uses the Gnome environment. Maybe assigning more RAM to your VM will speed things up. Also, I did notice that performance was faster when I was running the VM using VMware Fusion or Workstation than when using VirtualBox.

**Comment by lennyzeltser** [comment]
You should be able to install without errors now. Thanks to @digitalsleuth for looking into the Viper Framework problem and creating a workaround!
