### ISSUE TITLE
For consideration: dllcharacteristics.py tool

### ISSUE THREAD

**Issue by accidentalrebel** [REMnux/salt-states#173]
Hello again.

I just recently finished a new Python-based tool called `dllcharacteristics.py` found [here](https://github.com/accidentalrebel/dllcharacteristics.py). 

It is inspired by Didier Steven's [setdllcharacteristics](https://blog.didierstevens.com/2010/10/17/setdllcharacteristics/) tool. Just like the original it can set the flags for `DYNAMIC_BASE`, `NX_COMPAT`, and `FORCE_INTEGRITY` which is helpful for malware analysis and reverse engineering. 

I also added new features like the ability to set all other available DLL characteristics options and can also print whether each one is set or not.

Just a brief preview of what it can do:

```console
$ ./dllcharacteristics.py test.exe
Characteristics: 
- 0:  HIGH_ENTROPY_VA
- 1:  DYNAMIC_BASE
- 0:  FORCE_INTEGRITY
- 1:  NX_COMPAT
- 0:  NO_ISOLATION
- 0:  NO_SEH
- 0:  NO_BIND
- 0:  APPCONTAINER
- 0:  WDM_DRIVER
- 0:  GUARD_CF
- 1:  TERMINAL_SERVER_AWARE
```

```console
$ ./dllcharacteristics.py -s NO_BIND 1 -o output.exe test.exe
[INFO] Setting characteristic for NO_BIND to 1
[INFO] Writing to output.exe
```

```console
$ ./dllcharacteristics.py -d 0 -f 1 -n 0 -o output.exe test.exe
[INFO] Setting characteristic for DYNAMIC_BASE to 0
[INFO] Setting characteristic for NX_COMPAT to 0
[INFO] Setting characteristic for FORCE_INTEGRITY to 1
[INFO] Writing to output.exe
```

If this is something that could benefit Remnux users then I would be happy to make a pull request.

**Comment by lennyzeltser** [comment]
This sounds very useful! I will be glad to see the pull request.
