### ISSUE TITLE
Can we please add "p7zip-rar" to the distro?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#189]
This will help with rar version 5 files.  Thank you for your review!

**Comment by lennyzeltser** [comment]
Could you please check whether `unrar` or `rar` can handle this file format? I have a feeling that `rar` should be able to do it.

**Comment by citizenstaar** [comment]
unrar 0.0.1 does not

rar (5.50 - Trial Version) ,after I installed it, did work.  The working copy I was using was v2021.15.2.  Since rar works and I was not running the latest version of remnux I am going to close the issue.
