### ISSUE TITLE
yarascan invalid integer

### ISSUE THREAD

**Issue by wolf0x** [REMnux/salt-states#190]
vol.py -f "./Windows 7.vmem" --profile=Win7SP1x64_23418 yarascan -Y "211.211.211.211"

vol.py: error: option -Y: invalid integer value: '211.211.211.211'

Remnux-v7-focal

**Comment by PDX4N6** [comment]
the issue is not with volatility or REMnux.  It is the syntax in your command, on the REMnux version of volatility 2.6.1 you will need to use the -U flag when passing a string as a rule and the -y when calling a YARA rule file.  Hope this helps

<img width="610" alt="yarascan" src="https://user-images.githubusercontent.com/56566059/132576170-caf51197-f182-402a-b02e-d65f772e178a.png">

**Comment by lennyzeltser** [comment]
@PDX4N6, thank you for diagnosing this issue. @wolf0x, thank you for reporting it.

Yes, I completely forgot that to eliminate conflicts with other Volatility 2 plugins, I had to change the following `yarascan` options:

* `-Y` became `-U`
* `-C` became `-c`

To help prevent such confusion in the future I just added a note  about it to the [Volatility Framework entry on the REMnux documentation site](https://docs.remnux.org/discover-the-tools/perform+memory+forensics#volatility-framework).

**Comment by wolf0x** [comment]
I tried U but seems its invalid, do I need to update the REMnux?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________

**Comment by lennyzeltser** [comment]
@wolf0x, upgrading REMnux should affect this.

Sorry, I don't know why `-U` isn't working :-(

**Comment by digitalsleuth** [comment]
@wolf0x, any chance you can provide the output of `sudo remnux version` and the sha256sum of the OVA file you used to build the VM? This will help narrow down any changes in versions since you downloaded and spawned the VM you're currently using.

**Comment by digitalsleuth** [comment]
So, I've taken a look at this and can confirm that the `-U` option is working. Using a sample memory dump, I first checked to see if the netscan / connscan plugins would find any network connectivity. Confirming one viable IP address, I then used the following:

`vol.py -f zeus.dmp --profile=WinXPSP2x86 yarascan -U "65.54.81.89"` and 

`vol.py -f zeus.dmp --profile=WinXPSP2x86 yarascan --yara-rules "65.54.81.89"` 

Both of these had successful results:
![YARA_EXAMPLE](https://user-images.githubusercontent.com/62841822/132966792-3c2465fd-8264-4a74-a229-0faea81866e8.png)

@wolf0x, if you can provide me a copy of the Win7 memdump you're using, or use one that you know contains the IP address you're searching for, then that would definitely help confirm that the plugin works on your end.

**Comment by wolf0x** [comment]
Sleuth,

Many thanks, it could be working. Tkx.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
