### ISSUE TITLE
chromehistory plugin need updates in current remnux

### ISSUE THREAD

**Issue by wolf0x** [REMnux/salt-states#194]
it works after replaced by https://github.com/superponible/volatility-plugins

**Comment by digitalsleuth** [comment]
Hi @wolf0x , I'll take a look at this today. Can you let me know what wasn't working about it though before I do the update?

**Comment by lennyzeltser** [comment]
Thanks for addressing this, @digitalsleuth!

**Comment by wolf0x** [comment]
nice!
