### ISSUE TITLE
nodejs Certificate Expiry

### ISSUE THREAD

**Issue by digitalsleuth** [REMnux/salt-states#196]
While testing a recent update, I found that the nodejs certificate has expired, and thus apt will not accept the https request for the certificate update ([issue documented here](https://github.com/nodesource/distributions/issues/1266)).

Temporary solution is to replace the `https` entries in the `remnux/repos/nodejs.sls` file with `http`. I've already created a branch to add this change and am testing to ensure the full install works with this change. Once the test is complete, I will submit the pull request.

**Comment by lennyzeltser** [comment]
I issued a new salt-states release that includes your fix. Thanks, @digitalsleuth!
