### ISSUE TITLE
hash for pyinstxtractor.py needs to be updated to the latest. Unable to install latest version.

### ISSUE THREAD

**Issue by quinterod** [REMnux/salt-states#204]
[saltstack.log](https://github.com/REMnux/salt-states/files/8153472/saltstack.log)
  file_|-remnux-pyinstaller-source_|-/usr/local/bin/pyinstxtractor.py_|-managed:
    __id__: remnux-pyinstaller-source
    __run_num__: 458
    __sls__: remnux.scripts.pyinstaller-extractor
    changes: {}
    comment: Specified sha256 checksum for https://github.com/extremecoders-re/pyinstxtractor/raw/master/pyinstxtractor.py
      (1cbd5f17444e5fb316f777bdf41a80a08be55ea26376f73dc45388319495eb27) does not
      match actual checksum (6b0e61f5321e4b00b07ae487515fca5f471a9d96c7bd393fcb6472fed2d8fc75).
      If the 'source_hash' value refers to a remote file with multiple possible matches,
      then it may be necessary to set 'source_hash_name'.
    duration: 453.593
    name: /usr/local/bin/pyinstxtractor.py
    result: false
    start_time: '12:35:14.848132'

**Comment by digitalsleuth** [comment]
Morning @quinterod , Pull Request has already been submitted at #203 . Everything else should have installed fine though!

**Comment by quinterod** [comment]
Morning @digitalsleuth Thanks for the quick response. Ran again, same issue.
```

>> Running: /usr/local/bin/diec
>> Running: remnux-tools-detect-it-easy-install
>> Running: remnux-tools
>> Running: git+https://github.com/mindedsecurity/JStillery.git
>> Running: /usr/bin/jstillery
>> Running: remnux-node-packages
>> Running: cpan install Image::ExifTool
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

```
You say it should have installed fine? How can I verify?

**Comment by lennyzeltser** [comment]
@digitalsleuth added a pull request to fix the issue, but I didn't incorporate it into a formal release until a minute or so ago.

**Comment by lennyzeltser** [comment]
Should be good to go now.

**Comment by digitalsleuth** [comment]
@quinterod One way to verify is by looking in the saltstack.log and looking for any indications of "[ERROR   ]". The lines with "[ERROR   ] Can't" can be safely ignored, as they're only a python warning, not actually an error. In your initial log, the only line which had an ERROR was the pyinstxtractor hash.
