### ISSUE TITLE
Yara-rules and files with spaces

### ISSUE THREAD

**Issue by xme** [REMnux/salt-states#218]
The current /usr/local/bin/yara-rules script can't handle filenames with spaces.
Suggested:
```
#!/bin/bash
yara -w /usr/local/yara-rules/index.yar "${*}"
```

**Comment by digitalsleuth** [comment]
Hi @xme , any chance you can provide an example of the command line you're using so I can test it out?

**Comment by digitalsleuth** [comment]
Generated an example and tested, you are indeed correct about the issue. I've submitted a PR to address this and it should be resolved in the next release!
