### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by nr1z** [REMnux/salt-states#220]
what does this mean?

request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: getaddrinfo EAI_AGAIN api.github.com
HttpError: request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: getaddrinfo EAI_AGAIN api.github.com
    at /snapshot/remnux-cli/node_modules/@octokit/request/dist-node/index.js:107:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getValidReleases (/snapshot/remnux-cli/remnux-cli.js:293:18)
    at async run (/snapshot/remnux-cli/remnux-cli.js:738:26)
    at async main (/snapshot/remnux-cli/remnux-cli.js:778:5)

**Comment by digitalsleuth** [comment]
Hi @nr1z , the error "getaddrinfo" typically occurs if you have no internet connection, or your connection has temporarily dropped.

Can you confirm that you're able to browse the internet from within your VM and ping 8.8.8.8?

**Comment by nr1z** [comment]
that was it. do have to do the install process all over again or will it pick up where it left off?

**Comment by digitalsleuth** [comment]
Unfortunately you'll have to do it again, however some of the components will finish faster because they may have already completed during the last attempt.

Cheers!

**Comment by nr1z** [comment]
rg. thanks. that is all. :)
