### ISSUE TITLE
thug upgrade fails

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/salt-states#226]
```log
git_|-remnux-python3-packages-thug-git_|-https://github.com/buffer/thug_|-latest:
    __id__: remnux-python3-packages-thug-git
    __run_num__: 325
    __sls__: remnux.python3-packages.thug
    changes:
      new_tags: !!set
        v4.8: null
    comment: "Fetch failed. Set 'force_fetch' to True to force the fetch if the failure
      was due to not being able to fast-forward. Output of the fetch command follows:\n\nFrom
      https://github.com/buffer/thug\n   9c3e8e4f..2474217c  gh-pages   -> origin/gh-pages\n
      ! [rejected]          master     -> origin/master  (non-fast-forward)\n * [new
      tag]           v4.8       -> v4.8"
    duration: 1124.425
    name: https://github.com/buffer/thug
    result: false
    start_time: '15:18:31.126580'
```

**Comment by digitalsleuth** [comment]
Hi @seanthegeek , can you upload your saltstack.log so we can review it for potential causes?

**Comment by seanthegeek** [comment]
[saltstack.log](https://github.com/REMnux/salt-states/files/10611498/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @seanthegeek , I just took a look at the log and it seems like you might have just run the install at the same time as they released a new commit to thug. Testing it now, it seems fine. However, I've submitted a PR to pin the branch and set force_fetch: True to avoid this issue in the future.

**Comment by seanthegeek** [comment]
I was about to submit the same PR. Thanks!

**Comment by digitalsleuth** [comment]
Great minds :)

**Comment by seanthegeek** [comment]
I wonder if the same option should be added to the other git-based installs?

**Comment by digitalsleuth** [comment]
I'm reviewing them now actually

**Comment by lennyzeltser** [comment]
Thanks, @seanthegeek and @digitalsleuth. I issued a release earlier today that contains the Thug fix.
