### ISSUE TITLE
Droidlysis configuration error

### ISSUE THREAD

**Issue by gusgravious** [REMnux/salt-states#239]
Most likely a very poorly composed issue, hoping for some patience :) This may be the wrong place to submit this issue though this was the only place where droidlysis was mentioned in the repo.

I am runing a REMnux VM, up to date all of the latest and greatest installed.

Trying to run droidlysis resulted in a python error. After submitting an issue with the droidlysis maintainer I managed to figure out a few issues trying to use droidlysis in remnux.

The "general.conf" file for droidlysis contains the following lines:

    [tools]
    apktool = /home/axelle/softs/apktool_2.7.0.jar
    baksmali = /home/axelle/softs/baksmali-2.5.2.jar
    dex2jar = /home/axelle/softs/dex-tools-2.2-SNAPSHOT/d2j-dex2jar.sh
    procyon = /home/axelle/softs/procyon-decompiler-0.5.30.jar

1. All of the dependencies are installed, though they are linked/scripted in /usr/bin dropping the _version.jar part
2. Most/all were different/older versions then specified in the "general.conf"
3. The folder "/home/axelle" which is hardcoded does not exist

If installing droidlysis and dependencies in a local folder, then scripting the execution with "--config" specified works just fine. In any case, without a modified "general.conf" file execution of droidlysis fails

**Comment by digitalsleuth** [comment]
Hi @gusgravious , you are correct in that the lines you have listed above in the .conf file are the default which come with Droidlysis. The REMnux install of Droidlysis doesn't modify the .conf file for the file locations, but instead modifies the `droidconfig.py` file. However, with the recent change in their process to move away from global variables and to instead move to a .conf setup, our previous method no longer appears sufficient.

I'll work on fixing the droidlysis state file to account for the new .conf setup going forward.

Thanks for bringing this to our attention!

**Comment by digitalsleuth** [comment]
Hi @gusgravious , during my reworking of this state, I encountered an error with Droidlysis where the Dex2jar analysis won't run unless it's in verbose mode (issue raised [here](https://github.com/cryptax/droidlysis/issues/14)). Before I raise the new PR to fix the previous issue, I'm going to wait for a day or two to see if this gets fixed so I can continue testing that the changes will work properly. I'll still keep you posted on the progress.

Cheers!

**Comment by digitalsleuth** [comment]
The owner (cryptax) said he was going to be looking at droidlysis today to fix the issue I identified, then I can complete testing and hopefully push a new PR today.

Cheers!

**Comment by gusgravious** [comment]
Sorry for the late reply, I did get feedback from cryptax and just wanted to say thank you for maintaining a fantastic distro and fixing my issue
