### ISSUE TITLE
Possible wrong location for .malwapi.conf

### ISSUE THREAD

**Issue by ClaudioWayne** [REMnux/salt-states#244]
Hi,

I'm facing an error when installing remnux from scratch.

Error:
![Screenshot from 2023-06-20 13-06-53](https://github.com/REMnux/salt-states/assets/35531629/0d6e194c-c6da-4e4f-bd9b-6d42b0ccd4b0)

After digging into saltstack.log the error is eventually caused by a wrong path for  .malwapi.conf
![Screenshot from 2023-06-23 07-46-40](https://github.com/REMnux/salt-states/assets/35531629/2670f6ee-c24c-4856-9f43-1ef11ce826c3)

I found .malwapi.conf in a different path
![Screenshot from 2023-06-23 07-49-17](https://github.com/REMnux/salt-states/assets/35531629/2503032b-f48b-4abb-8b8e-6f64de6387cd)
`/opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf`

After I created ` /opt/malwoverview/lib/python3.8/site-packages/home/remnux/ ` manually and copied .malwapi.conf there, the installation was successful.
![Screenshot from 2023-06-23 08-14-30](https://github.com/REMnux/salt-states/assets/35531629/f0525cdf-dc9f-40a5-a916-fb82e0e43281)

---

Steps to repoduce:

- wget https://REMnux.org/remnux-cli
- mv remnux-cli remnux
- chmod +x remnux
- sudo mv remnux /usr/local/bin
- sudo apt install -y gnupg
- sudo remnux install

---

OS Infos:

![Screenshot from 2023-06-23 08-40-04](https://github.com/REMnux/salt-states/assets/35531629/3796248c-0af4-40e2-9fe2-a956ae1afc3d)

----

Greetings

ClaudioW

**Comment by digitalsleuth** [comment]
Hi @ClaudioWayne , did you happen to run the install as root (not sudo, but as the user root)? If so, that would cause the path to be incorrect because it is attempting to look for the "root" home directory.

**Comment by digitalsleuth** [comment]
Hi @ClaudioWayne , I've got the issue sorted out now, and will be submitting a PR shortly to fix this.
