### ISSUE TITLE
Error installing ''git+https://github.com/mindedsecurity/JStillery.git'':

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/salt-states#256]
The log doesn't provide much detail about what is going wrong, and I don't know anything about `npm` to troubleshoot it.
```
  npm_|-remnux-node-packages-jstillery_|-git+https://github.com/mindedsecurity/JStillery.git_|-installed:
    __id__: remnux-node-packages-jstillery
    __run_num__: 778
    __sls__: remnux.node-packages.jstillery
    changes: {}
    comment: 'Error installing ''git+https://github.com/mindedsecurity/JStillery.git'': '
    duration: 16006.611
    name: git+https://github.com/mindedsecurity/JStillery.git
    result: false
    start_time: '15:01:22.997332'
```

**Comment by digitalsleuth** [comment]
Hi @seanthegeek , can you attach the saltstack.log so we can troubleshoot further?

**Comment by seanthegeek** [comment]
The log entry above is the only related one I could find. There are a ton of python failures that we've been talk about in other issues.

**Comment by digitalsleuth** [comment]
@seanthegeek The log will contain other things which may have led to the failure and help us diagnose this issue. If you can, let us know if you'll be able to upload it so we can check it out. Cheers!

**Comment by seanthegeek** [comment]
It must have been a fluke with git, because it's working now and I didn't change anything (Python is still a mess, but I think I'm fixing that right now).
