### ISSUE TITLE
Ghidra package is outdated

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/salt-states#279]
Ghidra 10.4 is used in the REMnux PPA. The current latest release of Ghidra is 11.0.1.

**Comment by seanthegeek** [comment]
The latest version is now 11.0.3. @lennyzeltser, can you update the package?

**Comment by lennyzeltser** [comment]
I just updated the Ghidra package to version 11.0.3. The easiest way to get it on REMnux now is probably:

```
sudo apt update
sudo apt install ghidra
```
