### ISSUE TITLE
Tool suggestion: Magika 

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/salt-states#280]
Google recently released a new file type detection tool called Magika that is probably worth including in REMnux.

https://opensource.googleblog.com/2024/02/magika-ai-powered-fast-and-efficient-file-type-identification.html

https://google.github.io/magika/

https://github.com/google/magika

**Comment by digitalsleuth** [comment]
Hi @seanthegeek This looks quite interesting! I'll take a look and see how this can be integrated into REMnux. Thanks!

**Comment by lennyzeltser** [comment]
Thanks, I just released v2024.21.2 to include this, per @digitalsleuth's pull request.
