### ISSUE TITLE
No possible to install remnux on 16.04.6 Ubuntu

### ISSUE THREAD

**Issue by Erlopek** [REMnux/salt-states#3]
Hi
I'v tried many ways to install remnux on ubuntu 16.04 but it is not possible.
Remnux-cli doesn't work, tried Salt State way but I stucked on the third point .
git clone https://github.com:REMnux/states.git /srv/salt cannot be download because there is no such file as states.git in remnux repository.
I don't think that now with distro 16.04.6 LTS (Xenial Xerus) it is possible to install remnux.
If someone can show me trusted way to do it  I will be very greatfull :)

**Comment by nmb2** [comment]
Looks like an issue with the url, try this
https://github.com/REMnux/salt-states.git
