### ISSUE TITLE
apktool (REMnux7)- Can we add this please?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#47]
Can we add apktool?  Thank you for reviewing.

**Comment by lennyzeltser** [comment]
Done. Also added droidlysis; if you have experience with APK analysis, could you see whether it works properly, please?

**Comment by citizenstaar** [comment]
### droidlysis verification 

**Using the sample discussed here:**

[](https://twitter.com/malwrhunterteam/status/1259886844961005568)
[](https://www.virustotal.com/gui/file/1b990e94b254a1e81122ccf24c531dcbfeefe631e43b293516c424b75b14b061/detection)

**I was able to validate the documented procedures here:**

https://github.com/cryptax/droidlysis (Execution, Reporting, SQL Db Contents)

**I did a quick review of the output folder as well.  This appears to be working.**
