### ISSUE TITLE
DNSpy (Remnux 7) - Can we add this tool?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#48]
A different member of the community documented the installation and their usage of dnspy here:

https://ccifra.github.io/PortingWPFAppsToLinux/Overview.html

In the current build you need to add dotnet to the current wine install.

**Comment by lennyzeltser** [comment]
I looked into it, but getting this to work will take more time that I can allocate to this, since I'm not sure how to automate the addition of botnet to the Wine installation. The tool would be great to include, so will consider this for later.
