### ISSUE TITLE
de4dot (remnux 7) - Can we add this?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#49]
This is maintained by the debian team.  Details here:

https://packages.debian.org/sid/de4dot

**Comment by citizenstaar** [comment]
# [ERROR   ] Command '[u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u'libssl-dev']' failed with return code: 100
# [ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 de4dot : Depends: libdnlib2.1-cil (>= 2.1) but it is not installable
 libssl-dev : Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is to be installed
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.1-1ubuntu2.1~18.04.6 is to be installed
# [ERROR   ] stderr: Running scope as unit: run-rac2e4b00fde044038c358c4de725d0d3.scope
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
# [ERROR   ] retcode: 100
# [INFO    ] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${Architecture}', u'-W'] in directory '/home/remnux'
# [ERROR   ] Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-rac2e4b00fde044038c358c4de725d0d3.scope
      E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by citizenstaar** [comment]
**v2020.24.6**

**Comment by citizenstaar** [comment]
# [ERROR   ] Command '[u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options:
:=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u'libssl-dev']' failed wi
th return code: 100
# [ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 de4dot : Depends: libdnlib2.1-cil (>= 2.1) but it is not installable
 libssl-dev : Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is to be installed
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.1-1ubuntu2.1~18.04.6 is to be installed
# [ERROR   ] stderr: Running scope as unit: run-r29b209bf028844d9aaa14958da52a12b.scope
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
# [ERROR   ] retcode: 100
# [INFO    ] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${
Architecture}', u'-W'] in directory '/home/remnux'
# [ERROR   ] Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r29b209bf028844d9aaa14958da52a12b.scope
      E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by citizenstaar** [comment]
**v2020.25.1**

**Comment by lennyzeltser** [comment]
I attempted to repackage that Debian package for REMnux, but couldn't get it to build properly.

Another option is to run the tool using .NET Core, which seems to work, but I don't use de4dot, so cannot confirm that it's working properly. Would you be able to confirm that it works as intended by installing it this way:

```
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt update
sudo apt install -y dotnet-runtime-3.1
```

Then download `de4dot-netcoreapp3.1` from [the de4dot repo](https://github.com/0xd4d/de4dot/actions/runs/128842573) and save it as `de4dot-netcoreapp3.1.zip`. Extract the zip file:

```
unzip de4dot-netcoreapp3.1.zip -d de4dot
```

And try to execute it:

```
dotnet de4dot/de4dot.dll
```

Thanks!

**Comment by citizenstaar** [comment]
The code executes just fine.

**Comment by lennyzeltser** [comment]
Done. Thanks for the recommendation!
