### ISSUE TITLE
Powershell(REMnux7)- Can we add this please?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#51]
Please reference:

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#:~:text=Ubuntu%2018.04,-Installation%20via%20Package&text=PowerShell%20for%20Linux%20is%20published%20to,for%20easy%20installation%20and%20updates.&text=As%20superuser%2C%20register%20the%20Microsoft%20repository%20once.,sudo%20apt%2Dget%20install%20powershell%20.

Thank you for your review and consideration.

**Comment by lennyzeltser** [comment]
It's tempting, but I am wondering how useful this will be for malware analysis tasks. What scenarios do you have in mind?

**Comment by citizenstaar** [comment]
The following tasks from my POV:
- PSSession with Windows victim to remote execute files
- Local de-obfuscation of malicious powershell on Linux for IOC extraction 
- Local Debugging using Set-PSBreakpoint
- New automation stitching together other tools in the image to extract the code and then automate extracts

Thank you for taking the time to review.  I will continue to test tools already installed as well.

**Comment by lennyzeltser** [comment]
Great points, thanks! PowerShell is now on REMnux.
