### ISSUE TITLE
Ghidra(Remnux 7) - Frozen on "Language Search" when opening from shortcut

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#54]
## Issue

It seems if I run Ghidra after having a prior project it attempts to open the project and is stuck on load(you cannot cancel via the GUI).  

### Workaround
Kill running instance of java.  
Removal or movement of prior projects.  
Reopen Ghidra

**Comment by lennyzeltser** [comment]
Hmm.. I'm unable to reproduce the issue. I tried creating an empty project, then exited and returned to Ghidra without issues. I also tried importing an .exe file into the project, then exited and returned to Ghidra without problems.

Could you please clarify how you created the project to help me reproduce the issue?

Any chance rebooting your REMnux system will address the problem?

**Comment by citizenstaar** [comment]
Yes the problem persists after reboots.  

### TEST Environment: 
HOST: Windows 10, 64-bit  (Build 18362.900) 10.0.18362
HYPERVISOR:  VMware® Workstation 15 Pro 15.5.6 build-16341506

```
STEPS ( as user **remnux**):

1.  Under ~/Desktop/ created a sub folders called **~/Desktop/malware/working**  

2.  Staged [sample ](https://www.virustotal.com/gui/file/2dd57d67e486d6855df8235c15c9657f39e488ff5275d0ce0fcec7fc8566c64b/detection) in the **same folder**

3.  Created a non-shared project called various names

4.  Choose Import File and allow full analysis of file

5.  Close the application

6.  Reopen the application

```

![image](https://user-images.githubusercontent.com/17726673/84890355-4a6d8400-b068-11ea-9692-27c826e94aaf.png)

**Comment by citizenstaar** [comment]
**2020.25.1**

**Comment by lennyzeltser** [comment]
Thanks for the detailed instructions. I'm able to reproduce the issue now.

The easiest workaround I could find is to close CodeBrowser before exiting Ghidra. When I do that, I no longer encounter this issue.

Could you give this a try on your system to see if it works?

I can see that this is documented as a known issue here (reported on Kali):
https://github.com/NationalSecurityAgency/ghidra/issues/1822

Alas, I found no fix, but I hope the workaround above works and isn't too inconvenient.

**Comment by citizenstaar** [comment]
Perfect.  Thanks!
