### ISSUE TITLE
SSView (remnux 7) - Can we build and add shortcut?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#67]
See the following:

https://www.mitec.cz/ssv.html

Thank you for your review and consideration.

**Comment by lennyzeltser** [comment]
I used to use SSView awhile back, but now I feel it's been replaced by oledump and oletools. Given that it's not a native Unix tool, I'm not convinced it's needed on REMnux. What did you have in mind?

**Comment by citizenstaar** [comment]
From notes:

*  The tool does run given the current setup of remnux

*  The tool offers a non console view of SS files with familiar features in GUI to include multiple views, edit, and export features

*  Additional tools provide more options to the analyst even though they are overlapping

I agree with your statement and this is what I can offer back.  Thank you for your review.

**Comment by lennyzeltser** [comment]
Great points. I added the tool, thank you!
