### ISSUE TITLE
bearcommander (Remnux 7) - Can we add this please?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#68]
This is where the tool can be found:

https://github.com/hasherezade/bearparser

This is a sample of its usage:

https://github.com/hasherezade/bearparser/wiki/bearcommander

Thank you for your consideration and review.

**Comment by lennyzeltser** [comment]
Done. Thanks for the recommendation! 

The command is `bearcommander` and you should get it after running `remnux upgrade`. It seems to work, but please let me know if you discover otherwise.
