### ISSUE TITLE
Python-InquestLabs (Remnux 7) - Can we consider adding this tool?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#71]
Reference for tool can be found here:

https://github.com/inquest/python-inquestlabs

Thank you for your review.

**Comment by lennyzeltser** [comment]
Ince InQuest is a commercial tool, I'll leave it up the people who bought the tool to add the API libraries if they need them. Or do they have a free tool and have a broader applicability to the community?

**Comment by citizenstaar** [comment]
Like Chronicle Security's VirusTotal there is a InQuest free/open look at https://labs.inquest.net/ they state the following:

![image](https://user-images.githubusercontent.com/17726673/85284834-d8c57980-b45d-11ea-916c-368111651bff.png)

Apologies I thought I originally add this as part of the OP.

**Comment by citizenstaar** [comment]
My thanks again for your review...please consider adding this capability.
