### ISSUE TITLE
/usr/local/<TOOLHERE> (Remnux 7) - Can we update $PATH to include installed console applications?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#76]
Example is  Tekdefense Automater install.

**Comment by digitalsleuth** [comment]
@citizenstaar The /usr/local directory is used to temporarily stage the applications as they're installed, or to store tools which have static bindings to their modules which would break if we placed the core binary (in this case, Automater.py) in a directory without it's modules.

To rectify this problem, for each of the tools you find in /usr/local, we've either created symlink's to the tool in /usr/local/bin (as in Automater.py's case), or bash scripts in /usr/local/bin which are wrappers for the original location of the tool. This directory is not required to be in $PATH, as the symlinks and wrappers complete the task, and use the existing $PATH configuration.
If you run `which Automater.py`, you will see the symlink in /usr/local/bin, but if you do an `ls -la /usr/local/bin/Automater.py` you will see the symlink relationship.

Is there a specific tool which may be causing a problem in utilizing this method, or something with Automater.py?

**Comment by citizenstaar** [comment]
Ok I will test again and reopen if this is not the case.
