### ISSUE TITLE
Cleanup Unused $PATH and Directories (Remnux 7)

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#79]
Quick documentation:  references to games is uneeded and there appears to be some "leftover" material under /usr/local from other installations.

**Comment by lennyzeltser** [comment]
Some people might end up installing or already have games, so I'll leave the PATH as is.

Which artifacts did you find in /usr/local that were no longer needed? I just noticed /usr/local/test_data... anything else?

**Comment by citizenstaar** [comment]
This is what I have in my notes generally about $PATH:

**/snap/bin //this folder does not exist**

**/usr/local/games/  //empty**

**/usr/local/sbin //empty**

I have nothing additional to contribute on this topic.  But thank you for reviewing.
