### ISSUE TITLE
InQuest free/open (Remnux 7) - Tool Request

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#84]
Like Chronicle Security's VirusTotal there is a InQuest free/open look at https://labs.inquest.net/ they state the following:

![image](https://user-images.githubusercontent.com/17726673/85284834-d8c57980-b45d-11ea-916c-368111651bff.png)

Apologies I thought I originally add this as part of the OP.

_Originally posted by @citizenstaar in https://github.com/REMnux/salt-states/issues/71#issuecomment-647470792_

**Comment by citizenstaar** [comment]
Ref.  https://github.com/InQuest/python-inquestlabs

**Comment by lennyzeltser** [comment]
Thanks for the clarification regarding the free availability of this API. At this point, I'm not certain how wide-spread the underlying service is, so I'm hesitant to add it to REMnux just yet. Looks like people who need it will be easily add this themselves. I'll wait to see if other people request this.
