### ISSUE TITLE
Couldn't able to install

### ISSUE THREAD

**Issue by imkarthic** [REMnux/salt-states#9]
sudo salt-call --local state.sls remnux
[sudo] password for qwerty: 
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'home'
[CRITICAL] Rendering SLS 'base:remnux.config.wget' failed: Jinja variable 'dict object' has no attribute 'home'
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'home'
[CRITICAL] Rendering SLS 'base:remnux.config.curl' failed: Jinja variable 'dict object' has no attribute 'home'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:remnux.config.wget' failed: Jinja variable 'dict object' has no attribute 'home'
----------
    Rendering SLS 'base:remnux.config.curl' failed: Jinja variable 'dict object' has no attribute 'home'

**Comment by lennyzeltser** [comment]
This version of REMnux is still a work in progress. Sorry, but it's not ready for installation just yet.
